const defaultProducts = [
  {
    id: crypto.randomUUID(),
    name: 'Jaja z wolnego wybiegu (M/L)',
    price: 1.2,
    packaging: 'sztuka',
  },
  {
    id: crypto.randomUUID(),
    name: 'Jaja z wolnego wybiegu (S)',
    price: 0.7,
    packaging: 'sztuka',
  },
  {
    id: crypto.randomUUID(),
    name: 'Jaja z wolnego wybiegu (S/M)',
    price: 0.8,
    packaging: 'sztuka',
  },
  {
    id: crypto.randomUUID(),
    name: 'Jaja z wolnego wybiegu (M)',
    price: 1,
    packaging: 'sztuka',
  },
  {
    id: crypto.randomUUID(),
    name: 'Jaja z wolnego wybiegu (L/XL)',
    price: 1.3,
    packaging: 'sztuka',
  },

  { id: crypto.randomUUID(), name: 'Dynia', price: 8, packaging: 'kg' },
  { id: crypto.randomUUID(), name: 'Buraki', price: 6, packaging: 'kg' },
  { id: crypto.randomUUID(), name: 'Marchew', price: 7, packaging: 'kg' },
  { id: crypto.randomUUID(), name: 'Ziemniaki', price: 5, packaging: 'kg' },
  { id: crypto.randomUUID(), name: 'Cebula', price: 6, packaging: 'kg' },
  {
    id: crypto.randomUUID(),
    name: 'Czarna rzodkiew',
    price: 8,
    packaging: 'kg',
  },
  { id: crypto.randomUUID(), name: 'Czosnek', price: 4, packaging: 'główka' },
  {
    id: crypto.randomUUID(),
    name: 'Seler duży',
    price: 7,
    packaging: 'sztuka',
  },
  { id: crypto.randomUUID(), name: 'Por duży', price: 7, packaging: 'sztuka' },
  {
    id: crypto.randomUUID(),
    name: 'Ogórki kiszone',
    price: 15,
    packaging: 'słoik 0.9l',
  },
  {
    id: crypto.randomUUID(),
    name: 'Kapusta kiszona',
    price: 15,
    packaging: 'słoik 0.9l',
  },
  {
    id: crypto.randomUUID(),
    name: 'Zakwas buraczany 0.5l',
    price: 14,
    packaging: 'butelka 0.5l',
  },
  {
    id: crypto.randomUUID(),
    name: 'Zakwas buraczany 1l',
    price: 20,
    packaging: 'butelka 1l',
  },
  { id: crypto.randomUUID(), name: 'Rukola', price: 7, packaging: 'paczka' },
  { id: crypto.randomUUID(), name: 'Szpinak', price: 7, packaging: 'porcja' },
  { id: crypto.randomUUID(), name: 'Sałata', price: 7, packaging: 'paczka' },
  { id: crypto.randomUUID(), name: 'Szczaw', price: 7, packaging: 'paczka' },
  {
    id: crypto.randomUUID(),
    name: 'Słonecznik główka (duża)',
    price: 10,
    packaging: 'sztuka',
  },
  {
    id: crypto.randomUUID(),
    name: 'Słonecznik główka (średnia)',
    price: 7,
    packaging: 'sztuka',
  },
  {
    id: crypto.randomUUID(),
    name: 'Słonecznik główka (mała)',
    price: 4,
    packaging: 'sztuka',
  },
  { id: crypto.randomUUID(), name: 'Rabarbar', price: 7, packaging: 'wiązka' },
  {
    id: crypto.randomUUID(),
    name: 'Burak liściowy',
    price: 6,
    packaging: 'wiązka',
  },
  {
    id: crypto.randomUUID(),
    name: 'Natka pietruszki',
    price: 7,
    packaging: 'wiązka',
  },
  { id: crypto.randomUUID(), name: 'Koperek', price: 6, packaging: 'wiązka' },
  { id: crypto.randomUUID(), name: 'Lubczyk', price: 7, packaging: 'wiązka' },
  { id: crypto.randomUUID(), name: 'Jarmuż', price: 7, packaging: 'wiązka' },

  // Sezonowe produkty
  { id: crypto.randomUUID(), name: 'Cukinia', price: 3, packaging: 'sztuka' },
  { id: crypto.randomUUID(), name: 'Patison', price: 3, packaging: 'sztuka' },
  {
    id: crypto.randomUUID(),
    name: 'Kwiaty cukinii',
    price: 1.5,
    packaging: 'sztuka',
  },
  {
    id: crypto.randomUUID(),
    name: 'Liście selera',
    price: 5,
    packaging: 'wiązka',
  },
  {
    id: crypto.randomUUID(),
    name: 'Liście chrzanu',
    price: 7,
    packaging: 'wiązka',
  },
  { id: crypto.randomUUID(), name: 'Botwina', price: 7, packaging: 'wiązka' },
  {
    id: crypto.randomUUID(),
    name: 'Młoda marchew',
    price: 7,
    packaging: 'pęczek',
  },
  {
    id: crypto.randomUUID(),
    name: 'Szczypiorek',
    price: 7,
    packaging: 'wiązka',
  },
  {
    id: crypto.randomUUID(),
    name: 'Młody seler',
    price: 5,
    packaging: 'sztuka',
  },
  { id: crypto.randomUUID(), name: 'Młody por', price: 5, packaging: 'sztuka' },
  {
    id: crypto.randomUUID(),
    name: 'Koper do kiszenia',
    price: 5,
    packaging: 'wiązka',
  },
];

export default defaultProducts;
