export const defaultProducts = [
  {
    id: crypto.randomUUID(),
    name: 'Jaja z wolnego wybiegu (M/L)',
    price: 1.2,
    packaging: 'sztuka',
    src: '/jaja.jpg',
  },
  {
    id: crypto.randomUUID(),
    name: 'Jaja z wolnego wybiegu (S)',
    price: 0.7,
    packaging: 'sztuka',
    src: '/jaja.jpg',
  },
  {
    id: crypto.randomUUID(),
    name: 'Jaja z wolnego wybiegu (S/M)',
    price: 0.8,
    packaging: 'sztuka',
    src: '/jaja.jpg',
  },
  {
    id: crypto.randomUUID(),
    name: 'Jaja z wolnego wybiegu (M)',
    price: 1,
    packaging: 'sztuka',
    src: '/jaja.jpg',
  },
  {
    id: crypto.randomUUID(),
    name: 'Jaja z wolnego wybiegu (L/XL)',
    price: 1.3,
    packaging: 'sztuka',
    src: '/jaja.jpg',
  },
  {
    id: crypto.randomUUID(),
    name: 'Dynia',
    price: 8,
    packaging: 'kg',
    src: '/dynia.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Buraki',
    price: 6,
    packaging: 'kg',
    src: '/buraki.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Marchew',
    price: 7,
    packaging: 'kg',
    src: '/marchew.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Ziemniaki',
    price: 5,
    packaging: 'kg',
    src: '/ziemniaki.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Cebula',
    price: 6,
    packaging: 'kg',
    src: '/cebula.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Czarna rzodkiew',
    price: 8,
    packaging: 'kg',
    src: '/czarna_rzodkiew.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Czosnek',
    price: 4,
    packaging: 'główka',
    src: '/czosnek.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Seler duży',
    price: 7,
    packaging: 'sztuka',
    src: '/seler.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Por duży',
    price: 7,
    packaging: 'sztuka',
    src: '/por.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Ogórki kiszone',
    price: 15,
    packaging: 'słoik 0.9l',
    src: '/ogórki_kiszone.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Kapusta kiszona',
    price: 15,
    packaging: 'słoik 0.9l',
    src: '/kapusta_kiszona.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Zakwas buraczany 0.5l',
    price: 14,
    packaging: 'butelka 0.5l',
    src: '/zakwas_buraczany.jpg',
  },
  {
    id: crypto.randomUUID(),
    name: 'Zakwas buraczany 1l',
    price: 20,
    packaging: 'butelka 1l',
    src: '/zakwas_buraczany.jpg',
  },
  {
    id: crypto.randomUUID(),
    name: 'Rukola',
    price: 7,
    packaging: 'paczka',
    src: '/rukola.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Szpinak',
    price: 7,
    packaging: 'porcja',
    src: '/szpinak.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Sałata',
    price: 7,
    packaging: 'paczka',
    src: '/sałata.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Szczaw',
    price: 7,
    packaging: 'paczka',
    src: '/szczaw.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Słonecznik główka (duża)',
    price: 10,
    packaging: 'sztuka',
    src: '/słonecznik.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Słonecznik główka (średnia)',
    price: 7,
    packaging: 'sztuka',
    src: '/słonecznik.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Słonecznik główka (mała)',
    price: 4,
    packaging: 'sztuka',
    src: '/słonecznik.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Rabarbar',
    price: 7,
    packaging: 'wiązka',
    src: '/rabarbar.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Burak liściowy',
    price: 6,
    packaging: 'wiązka',
    src: '/burak_liściowy.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Natka pietruszki',
    price: 7,
    packaging: 'wiązka',
    src: '/natka_pietruszki.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Koperek',
    price: 6,
    packaging: 'wiązka',
    src: '/koperek.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Lubczyk',
    price: 7,
    packaging: 'wiązka',
    src: '/lubczyk.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Jarmuż',
    price: 7,
    packaging: 'wiązka',
    src: '/jarmuż.png',
  },

  // Sezonowe produkty
  {
    id: crypto.randomUUID(),
    name: 'Cukinia',
    price: 3,
    packaging: 'sztuka',
    src: '/cukinia.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Patison',
    price: 3,
    packaging: 'sztuka',
    src: '/patison.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Kwiaty cukinii',
    price: 1.5,
    packaging: 'sztuka',
    src: '/kwiaty_cukinii.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Liście selera',
    price: 5,
    packaging: 'wiązka',
    src: '/liście_selera.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Liście chrzanu',
    price: 7,
    packaging: 'wiązka',
    src: '/liście_chrzanu.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Botwina',
    price: 7,
    packaging: 'wiązka',
    src: '/botwina.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Młoda marchew',
    price: 7,
    packaging: 'pęczek',
    src: '/młoda_marchew.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Szczypiorek',
    price: 7,
    packaging: 'wiązka',
    src: '/szczypiorek.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Młody seler',
    price: 5,
    packaging: 'sztuka',
    src: '/młody_seler.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Młody por',
    price: 5,
    packaging: 'sztuka',
    src: '/młody_por.png',
  },
  {
    id: crypto.randomUUID(),
    name: 'Koper do kiszenia',
    price: 5,
    packaging: 'wiązka',
    src: '/koper_do_kiszenia.png',
  },
];
export const defaultClients = [
  { address: 'Piotra Czajkowskiego 63b/8', phone: '608 078 465' },
  { address: 'Piotra Czajkowskiego 29a/8', phone: '606 766 578' },
  { address: 'Iwiny, Polna 20b', phone: '882 701 170' },
  { address: 'Dobrzykowice, Błękitna 43a', phone: '606 851 119' },
  { address: 'Kiełczów, Wrocławska 76', phone: '690 013 757' },
  { address: 'Długołęka, Zachodnia 27', phone: '723 371 035' },
  { address: 'Długołęka, Wschodnia 23', phone: '724 344 224' },
  { address: 'Hermanowska 38/19', phone: '513 162 775' },
  { address: 'Dziadoszańska 9', phone: '662 466 012' },
  { address: 'Marii Konopnickiej 64A', phone: '509 427 587' },
  { address: 'Poświęcka 22A/14', phone: '693 633 340' },
  { address: 'Heleny Boguszewskiej 5', phone: '605 242 283' },
  { address: 'Stanisława Kunickiego 39/6', phone: '605 609 318' },
  { address: 'Wilczyce, Dębowa 4D', phone: '519 596 212' },
  { address: 'Perkusyjna 19A/11', phone: '508 142 633' },
  { address: 'Onufrego Zagłoby 14', phone: '503 758 837' },
  { address: 'Łukowa 11', phone: '607 057 255' },
  { address: 'Mokrzańska 24/5', phone: '663 282 765' },
  { address: 'Wilczyce, Radosna 2/2', phone: '577 236 006' },
  { address: 'Wysoka, Łagodna 6', phone: '501 257 561' },
];
